#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.

menuentry 'Garuda Linux (Sway)' --class garuda --class gnu-linux --class gnu --class os {
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 8bd3f167-6c5c-4577-ab47-9965d1964e7f
    echo 'Carregando Garuda Sway...'
    linux /@/boot/vmlinuz-linux-zen root=UUID=8bd3f167-6c5c-4577-ab47-9965d1964e7f rw rootflags=subvol=@ loglevel=3 quiet nowatchdog
    initrd /@/boot/initramfs-linux-zen.img
}


menuentry "NixOS 25.11" {
    insmod part_gpt
    insmod fat
    insmod ext2
    search --no-floppy --fs-uuid --set=root D8D9-D120
    linux /EFI/nixos/h02zlysrch5fflcj3665nk53fx007c45-linux-6.12.87-bzImage.efi init=/nix/store/zw0akp3nfywks2xwixn3cp56jj65hgk0-nixos-system-nixos-25.11.10684.8fd9daa3db09/init root=UUID=9e054757-5096-4e05-a471-26731c8043bd loglevel=4
    initrd /EFI/nixos/0arrhqdiakbmpgpcjwl98qkm5kg1fkx7-initrd-linux-6.12.87-initrd.efi
}
